# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/aaron/Desktop/git_article/RTL/bestAlgorithm_RTL/bestAlgorithm_RTL.cache/wt [current_project]
set_property parent.project_path C:/Users/aaron/Desktop/git_article/RTL/bestAlgorithm_RTL/bestAlgorithm_RTL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/aaron/Desktop/git_article/vivadoProjects/bubbleSort/solution1 [current_project]
read_verilog -library xil_defaultlib C:/Users/aaron/Desktop/git_article/vivadoProjects/bubbleSort/solution1/syn/verilog/bubbleSort.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top bubbleSort -part xc7a200tfbg676-2


write_checkpoint -force -noxdef bubbleSort.dcp

catch { report_utilization -file bubbleSort_utilization_synth.rpt -pb bubbleSort_utilization_synth.pb }
