-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity heapSort is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    indexOutputData : IN STD_LOGIC_VECTOR (7 downto 0);
    operation_V : IN STD_LOGIC_VECTOR (0 downto 0);
    A_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_we0 : OUT STD_LOGIC;
    A_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    A_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    A_ce1 : OUT STD_LOGIC;
    A_we1 : OUT STD_LOGIC;
    A_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    A_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of heapSort is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "heapSort,hls_ip_2016_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.854000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=259,HLS_SYN_LUT=321}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_st7_fsm_6 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_st8_fsm_7 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_st9_fsm_8 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_st10_fsm_9 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_FF : STD_LOGIC_VECTOR (8 downto 0) := "011111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_100 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_25 : BOOLEAN;
    signal reg_126 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_54 : BOOLEAN;
    signal ap_sig_cseq_ST_st9_fsm_8 : STD_LOGIC;
    signal ap_sig_61 : BOOLEAN;
    signal operation_V_load_load_fu_132_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_149_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_reg_194 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_81 : BOOLEAN;
    signal tmp_2_fu_141_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal A_addr_6_reg_202 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_93 : BOOLEAN;
    signal tmp_3_fu_159_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_i_cast_cast_fu_172_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_1_i_cast_cast_reg_208 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_cseq_ST_st7_fsm_6 : STD_LOGIC;
    signal ap_sig_105 : BOOLEAN;
    signal i_2_fu_177_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_2_reg_213 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_ap_done : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_ap_idle : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_ap_ready : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_startA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_endA : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce0 : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_we0 : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce1 : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_we1 : STD_LOGIC;
    signal grp_heapSort_maxHeapify_noRecurv_fu_115_A_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_i_reg_80 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_134 : BOOLEAN;
    signal i_1_i_reg_92 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_cseq_ST_st8_fsm_7 : STD_LOGIC;
    signal ap_sig_148 : BOOLEAN;
    signal p_0_reg_104 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_reg_grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start : STD_LOGIC := '0';
    signal tmp_fu_136_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_12_i_fu_167_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_cseq_ST_st6_fsm_5 : STD_LOGIC;
    signal ap_sig_175 : BOOLEAN;
    signal i_1_i_cast_fu_155_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_cseq_ST_st10_fsm_9 : STD_LOGIC;
    signal ap_sig_209 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);

    component heapSort_maxHeapify_noRecurv IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        startA : IN STD_LOGIC_VECTOR (7 downto 0);
        endA : IN STD_LOGIC_VECTOR (9 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_we0 : OUT STD_LOGIC;
        A_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        A_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        A_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        A_ce1 : OUT STD_LOGIC;
        A_we1 : OUT STD_LOGIC;
        A_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        A_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_heapSort_maxHeapify_noRecurv_fu_115 : component heapSort_maxHeapify_noRecurv
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start,
        ap_done => grp_heapSort_maxHeapify_noRecurv_fu_115_ap_done,
        ap_idle => grp_heapSort_maxHeapify_noRecurv_fu_115_ap_idle,
        ap_ready => grp_heapSort_maxHeapify_noRecurv_fu_115_ap_ready,
        startA => grp_heapSort_maxHeapify_noRecurv_fu_115_startA,
        endA => grp_heapSort_maxHeapify_noRecurv_fu_115_endA,
        A_address0 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_address0,
        A_ce0 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce0,
        A_we0 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_we0,
        A_d0 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_d0,
        A_q0 => A_q0,
        A_address1 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_address1,
        A_ce1 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce1,
        A_we1 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_we1,
        A_d1 => grp_heapSort_maxHeapify_noRecurv_fu_115_A_d1,
        A_q1 => A_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = tmp_2_fu_141_p3)) or (ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6))) then 
                    ap_reg_grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_heapSort_maxHeapify_noRecurv_fu_115_ap_ready)) then 
                    ap_reg_grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_1_i_reg_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = tmp_2_fu_141_p3)))) then 
                i_1_i_reg_92 <= ap_const_lv9_FF;
            elsif ((not((ap_const_logic_0 = grp_heapSort_maxHeapify_noRecurv_fu_115_ap_done)) and (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
                i_1_i_reg_92 <= i_2_reg_213;
            end if; 
        end if;
    end process;

    i_i_reg_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)) and (operation_V_load_load_fu_132_p1 = ap_const_lv1_0))) then 
                i_i_reg_80 <= ap_const_lv8_7F;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_logic_0 = grp_heapSort_maxHeapify_noRecurv_fu_115_ap_done)))) then 
                i_i_reg_80 <= i_reg_194;
            end if; 
        end if;
    end process;

    p_0_reg_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_3_fu_159_p3)))) then 
                p_0_reg_104 <= ap_const_lv16_0;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8)) then 
                p_0_reg_104 <= A_q0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_3_fu_159_p3))) then
                A_addr_6_reg_202 <= tmp_12_i_fu_167_p1(8 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6)) then
                    i_1_i_cast_cast_reg_208(8 downto 0) <= i_1_i_cast_cast_fu_172_p1(8 downto 0);
                i_2_reg_213 <= i_2_fu_177_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = tmp_2_fu_141_p3))) then
                i_reg_194 <= i_fu_149_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st9_fsm_8))) then
                reg_126 <= A_q0;
            end if;
        end if;
    end process;
    i_1_i_cast_cast_reg_208(9) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, operation_V_load_load_fu_132_p1, tmp_2_fu_141_p3, tmp_3_fu_159_p3, grp_heapSort_maxHeapify_noRecurv_fu_115_ap_done)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if ((not((ap_start = ap_const_logic_0)) and not((operation_V_load_load_fu_132_p1 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_st9_fsm_8;
                elsif ((not((ap_start = ap_const_logic_0)) and (operation_V_load_load_fu_132_p1 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((ap_const_lv1_0 = tmp_2_fu_141_p3))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st3_fsm_2 => 
                if (not((ap_const_logic_0 = grp_heapSort_maxHeapify_noRecurv_fu_115_ap_done))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st4_fsm_3 => 
                if (not((ap_const_lv1_0 = tmp_3_fu_159_p3))) then
                    ap_NS_fsm <= ap_ST_st10_fsm_9;
                else
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                end if;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st6_fsm_5;
            when ap_ST_st6_fsm_5 => 
                ap_NS_fsm <= ap_ST_st7_fsm_6;
            when ap_ST_st7_fsm_6 => 
                ap_NS_fsm <= ap_ST_st8_fsm_7;
            when ap_ST_st8_fsm_7 => 
                if (not((ap_const_logic_0 = grp_heapSort_maxHeapify_noRecurv_fu_115_ap_done))) then
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                else
                    ap_NS_fsm <= ap_ST_st8_fsm_7;
                end if;
            when ap_ST_st9_fsm_8 => 
                ap_NS_fsm <= ap_ST_st10_fsm_9;
            when ap_ST_st10_fsm_9 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;

    A_address0_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0, A_addr_6_reg_202, ap_sig_cseq_ST_st4_fsm_3, grp_heapSort_maxHeapify_noRecurv_fu_115_A_address0, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7, tmp_fu_136_p1, ap_sig_cseq_ST_st6_fsm_5)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then 
            A_address0 <= A_addr_6_reg_202;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then 
            A_address0 <= ap_const_lv8_0;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
            A_address0 <= tmp_fu_136_p1(8 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_address0 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_address0;
        else 
            A_address0 <= "XXXXXXXX";
        end if; 
    end process;


    A_address1_assign_proc : process(ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st4_fsm_3, grp_heapSort_maxHeapify_noRecurv_fu_115_A_address1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7, tmp_12_i_fu_167_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
            A_address1 <= ap_const_lv8_0;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then 
            A_address1 <= tmp_12_i_fu_167_p1(8 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_address1 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_address1;
        else 
            A_address1 <= "XXXXXXXX";
        end if; 
    end process;


    A_ce0_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0, ap_sig_cseq_ST_st4_fsm_3, grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce0, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7, ap_sig_cseq_ST_st6_fsm_5)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0))) or (ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) or (ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5))) then 
            A_ce0 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_ce0 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce0;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_ce1_assign_proc : process(ap_sig_cseq_ST_st5_fsm_4, ap_sig_cseq_ST_st4_fsm_3, grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4) or (ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3))) then 
            A_ce1 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_ce1 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_ce1;
        else 
            A_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    A_d0_assign_proc : process(reg_126, grp_heapSort_maxHeapify_noRecurv_fu_115_A_d0, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7, ap_sig_cseq_ST_st6_fsm_5)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then 
            A_d0 <= reg_126;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_d0 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_d0;
        else 
            A_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    A_d1_assign_proc : process(A_q1, ap_sig_cseq_ST_st5_fsm_4, grp_heapSort_maxHeapify_noRecurv_fu_115_A_d1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
            A_d1 <= A_q1;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_d1 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_d1;
        else 
            A_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    A_we0_assign_proc : process(grp_heapSort_maxHeapify_noRecurv_fu_115_A_we0, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7, ap_sig_cseq_ST_st6_fsm_5)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5))) then 
            A_we0 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_we0 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_we0;
        else 
            A_we0 <= ap_const_logic_0;
        end if; 
    end process;


    A_we1_assign_proc : process(ap_sig_cseq_ST_st5_fsm_4, grp_heapSort_maxHeapify_noRecurv_fu_115_A_we1, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4))) then 
            A_we1 <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) or (ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7))) then 
            A_we1 <= grp_heapSort_maxHeapify_noRecurv_fu_115_A_we1;
        else 
            A_we1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_sig_cseq_ST_st10_fsm_9)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_sig_cseq_ST_st10_fsm_9)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st10_fsm_9)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= p_0_reg_104;

    ap_sig_105_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_105 <= (ap_const_lv1_1 = ap_CS_fsm(6 downto 6));
    end process;


    ap_sig_134_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_134 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_148_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_148 <= (ap_const_lv1_1 = ap_CS_fsm(7 downto 7));
    end process;


    ap_sig_175_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_175 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_209_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_209 <= (ap_const_lv1_1 = ap_CS_fsm(9 downto 9));
    end process;


    ap_sig_25_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_25 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_54_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_54 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_61_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_61 <= (ap_const_lv1_1 = ap_CS_fsm(8 downto 8));
    end process;


    ap_sig_81_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_81 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_93_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_93 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_cseq_ST_st10_fsm_9_assign_proc : process(ap_sig_209)
    begin
        if (ap_sig_209) then 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st10_fsm_9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_25)
    begin
        if (ap_sig_25) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_81)
    begin
        if (ap_sig_81) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_134)
    begin
        if (ap_sig_134) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_93)
    begin
        if (ap_sig_93) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_54)
    begin
        if (ap_sig_54) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st6_fsm_5_assign_proc : process(ap_sig_175)
    begin
        if (ap_sig_175) then 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st7_fsm_6_assign_proc : process(ap_sig_105)
    begin
        if (ap_sig_105) then 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st8_fsm_7_assign_proc : process(ap_sig_148)
    begin
        if (ap_sig_148) then 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st8_fsm_7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st9_fsm_8_assign_proc : process(ap_sig_61)
    begin
        if (ap_sig_61) then 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st9_fsm_8 <= ap_const_logic_0;
        end if; 
    end process;

    grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start <= ap_reg_grp_heapSort_maxHeapify_noRecurv_fu_115_ap_start;

    grp_heapSort_maxHeapify_noRecurv_fu_115_endA_assign_proc : process(i_1_i_cast_cast_reg_208, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then 
            grp_heapSort_maxHeapify_noRecurv_fu_115_endA <= i_1_i_cast_cast_reg_208;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
            grp_heapSort_maxHeapify_noRecurv_fu_115_endA <= ap_const_lv10_100;
        else 
            grp_heapSort_maxHeapify_noRecurv_fu_115_endA <= "XXXXXXXXXX";
        end if; 
    end process;


    grp_heapSort_maxHeapify_noRecurv_fu_115_startA_assign_proc : process(i_i_reg_80, ap_sig_cseq_ST_st3_fsm_2, ap_sig_cseq_ST_st8_fsm_7)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_7)) then 
            grp_heapSort_maxHeapify_noRecurv_fu_115_startA <= ap_const_lv8_0;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
            grp_heapSort_maxHeapify_noRecurv_fu_115_startA <= i_i_reg_80;
        else 
            grp_heapSort_maxHeapify_noRecurv_fu_115_startA <= "XXXXXXXX";
        end if; 
    end process;

    i_1_i_cast_cast_fu_172_p1 <= std_logic_vector(resize(unsigned(i_1_i_reg_92),10));
        i_1_i_cast_fu_155_p1 <= std_logic_vector(resize(signed(i_1_i_reg_92),16));

    i_2_fu_177_p2 <= std_logic_vector(unsigned(i_1_i_reg_92) + unsigned(ap_const_lv9_1FF));
    i_fu_149_p2 <= std_logic_vector(unsigned(i_i_reg_80) + unsigned(ap_const_lv8_FF));
    operation_V_load_load_fu_132_p1 <= operation_V;
    tmp_12_i_fu_167_p1 <= std_logic_vector(resize(unsigned(i_1_i_cast_fu_155_p1),64));
    tmp_2_fu_141_p3 <= i_i_reg_80(7 downto 7);
    tmp_3_fu_159_p3 <= i_1_i_reg_92(8 downto 8);
        tmp_fu_136_p1 <= std_logic_vector(resize(signed(indexOutputData),64));

end behav;
