// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "heapSort_noRecurv.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic heapSort_noRecurv::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic heapSort_noRecurv::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> heapSort_noRecurv::ap_ST_st1_fsm_0 = "1";
const sc_lv<15> heapSort_noRecurv::ap_ST_st2_fsm_1 = "10";
const sc_lv<15> heapSort_noRecurv::ap_ST_st3_fsm_2 = "100";
const sc_lv<15> heapSort_noRecurv::ap_ST_st4_fsm_3 = "1000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st5_fsm_4 = "10000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st6_fsm_5 = "100000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<15> heapSort_noRecurv::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> heapSort_noRecurv::ap_const_lv1_1 = "1";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_1 = "1";
const sc_lv<1> heapSort_noRecurv::ap_const_lv1_0 = "0";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_3 = "11";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_4 = "100";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_5 = "101";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_B = "1011";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_D = "1101";
const sc_lv<6> heapSort_noRecurv::ap_const_lv6_17 = "10111";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_2 = "10";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_E = "1110";
const sc_lv<7> heapSort_noRecurv::ap_const_lv7_2F = "101111";
const sc_lv<6> heapSort_noRecurv::ap_const_lv6_0 = "000000";
const sc_lv<7> heapSort_noRecurv::ap_const_lv7_30 = "110000";
const sc_lv<64> heapSort_noRecurv::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_C = "1100";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_6 = "110";
const sc_lv<6> heapSort_noRecurv::ap_const_lv6_3F = "111111";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_1F = "11111";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_17 = "10111";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_1E = "11110";
const sc_lv<9> heapSort_noRecurv::ap_const_lv9_181 = "110000001";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_8 = "1000";
const sc_lv<8> heapSort_noRecurv::ap_const_lv8_7F = "1111111";
const sc_lv<32> heapSort_noRecurv::ap_const_lv32_36 = "110110";
const sc_lv<7> heapSort_noRecurv::ap_const_lv7_7F = "1111111";

heapSort_noRecurv::heapSort_noRecurv(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116 = new heapSort_noRecurv_maxHeapify_noRecurv("grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116");
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->ap_clk(ap_clk);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->ap_rst(ap_rst);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->ap_start(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->ap_done(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->ap_idle(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_idle);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->ap_ready(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_ready);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_address0(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address0);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_ce0(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce0);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_we0(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we0);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_d0(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d0);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_q0(A_q0);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_address1(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address1);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_ce1(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce1);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_we1(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we1);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_d1(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d1);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->A_q1(A_q1);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->startA(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA);
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116->endA(grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA);
    heapSort_noRecurv_sitofp_32ns_32_6_U5 = new heapSort_noRecurv_sitofp_32ns_32_6<1,6,32,32>("heapSort_noRecurv_sitofp_32ns_32_6_U5");
    heapSort_noRecurv_sitofp_32ns_32_6_U5->clk(ap_clk);
    heapSort_noRecurv_sitofp_32ns_32_6_U5->reset(ap_rst);
    heapSort_noRecurv_sitofp_32ns_32_6_U5->din0(p_Val2_s_reg_347);
    heapSort_noRecurv_sitofp_32ns_32_6_U5->ce(ap_var_for_const0);
    heapSort_noRecurv_sitofp_32ns_32_6_U5->dout(grp_fu_128_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( A_addr_6_reg_321 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( tmp_i_fu_157_p1 );

    SC_METHOD(thread_A_address1);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_A_ce1);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_A_d0);
    sensitive << ( A_q1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_A_d1);
    sensitive << ( tmp_2_i_reg_352 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_A_we0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_A_we1);
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_31_fu_149_p3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_31_fu_149_p3 );

    SC_METHOD(thread_ap_sig_101);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_110);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_119);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_150);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_162);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_181);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_191);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_57);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_86);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_110 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_181 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_119 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_162 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_30 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_150 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_74 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_86 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_101 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_191 );

    SC_METHOD(thread_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start);
    sensitive << ( ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start );

    SC_METHOD(thread_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_assign_reg_104 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA);
    sensitive << ( i_reg_92 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_i_2_fu_139_p2);
    sensitive << ( i_reg_92 );

    SC_METHOD(thread_i_3_fu_299_p2);
    sensitive << ( i_assign_reg_104 );

    SC_METHOD(thread_i_assign_cast_fu_145_p1);
    sensitive << ( i_assign_reg_104 );

    SC_METHOD(thread_isNeg_fu_198_p3);
    sensitive << ( sh_assign_fu_192_p2 );

    SC_METHOD(thread_loc_V_2_fu_184_p1);
    sensitive << ( p_Val2_5_fu_162_p1 );

    SC_METHOD(thread_loc_V_fu_174_p4);
    sensitive << ( p_Val2_5_fu_162_p1 );

    SC_METHOD(thread_p_Result_2_fu_224_p3);
    sensitive << ( loc_V_2_reg_331 );

    SC_METHOD(thread_p_Val2_5_fu_162_p1);
    sensitive << ( A_q0 );

    SC_METHOD(thread_p_Val2_7_i_i_i_fu_286_p2);
    sensitive << ( p_Val2_8_fu_279_p3 );

    SC_METHOD(thread_p_Val2_8_fu_279_p3);
    sensitive << ( isNeg_reg_336 );
    sensitive << ( tmp_s_fu_265_p1 );
    sensitive << ( tmp_27_fu_269_p4 );

    SC_METHOD(thread_p_Val2_s_fu_292_p3);
    sensitive << ( p_Result_s_reg_326 );
    sensitive << ( p_Val2_8_fu_279_p3 );
    sensitive << ( p_Val2_7_i_i_i_fu_286_p2 );

    SC_METHOD(thread_sh_assign_2_cast_cast_fu_238_p1);
    sensitive << ( sh_assign_2_reg_341 );

    SC_METHOD(thread_sh_assign_2_cast_fu_235_p1);
    sensitive << ( sh_assign_2_reg_341 );

    SC_METHOD(thread_sh_assign_2_fu_216_p3);
    sensitive << ( isNeg_fu_198_p3 );
    sensitive << ( sh_assign_fu_192_p2 );
    sensitive << ( tmp_2_i_i_i_cast_fu_212_p1 );

    SC_METHOD(thread_sh_assign_fu_192_p2);
    sensitive << ( tmp_i_i_i_i_cast1_fu_188_p1 );

    SC_METHOD(thread_tmp_27_fu_269_p4);
    sensitive << ( tmp_6_i_i_i_fu_251_p2 );

    SC_METHOD(thread_tmp_2_i_i_i_cast_fu_212_p1);
    sensitive << ( tmp_2_i_i_i_fu_206_p2 );

    SC_METHOD(thread_tmp_2_i_i_i_fu_206_p2);
    sensitive << ( loc_V_fu_174_p4 );

    SC_METHOD(thread_tmp_31_fu_149_p3);
    sensitive << ( i_assign_reg_104 );

    SC_METHOD(thread_tmp_37_fu_257_p3);
    sensitive << ( tmp_4_i_i_i_fu_245_p2 );

    SC_METHOD(thread_tmp_3_i_i_i_fu_241_p1);
    sensitive << ( sh_assign_2_cast_fu_235_p1 );

    SC_METHOD(thread_tmp_4_i_i_i_fu_245_p2);
    sensitive << ( p_Result_2_fu_224_p3 );
    sensitive << ( sh_assign_2_cast_cast_fu_238_p1 );

    SC_METHOD(thread_tmp_6_i_i_i_fu_251_p2);
    sensitive << ( tmp_i_i_i_fu_231_p1 );
    sensitive << ( tmp_3_i_i_i_fu_241_p1 );

    SC_METHOD(thread_tmp_fu_131_p3);
    sensitive << ( i_reg_92 );

    SC_METHOD(thread_tmp_i_fu_157_p1);
    sensitive << ( i_assign_cast_fu_145_p1 );

    SC_METHOD(thread_tmp_i_i_i_fu_231_p1);
    sensitive << ( p_Result_2_fu_224_p3 );

    SC_METHOD(thread_tmp_i_i_i_i_cast1_fu_188_p1);
    sensitive << ( loc_V_fu_174_p4 );

    SC_METHOD(thread_tmp_s_fu_265_p1);
    sensitive << ( tmp_37_fu_257_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_131_p3 );
    sensitive << ( tmp_31_fu_149_p3 );
    sensitive << ( grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000001";
    ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "heapSort_noRecurv_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_we0, "(port)A_we0");
    sc_trace(mVcdFile, A_d0, "(port)A_d0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, A_address1, "(port)A_address1");
    sc_trace(mVcdFile, A_ce1, "(port)A_ce1");
    sc_trace(mVcdFile, A_we1, "(port)A_we1");
    sc_trace(mVcdFile, A_d1, "(port)A_d1");
    sc_trace(mVcdFile, A_q1, "(port)A_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_30, "ap_sig_30");
    sc_trace(mVcdFile, i_2_fu_139_p2, "i_2_fu_139_p2");
    sc_trace(mVcdFile, i_2_reg_308, "i_2_reg_308");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_57, "ap_sig_57");
    sc_trace(mVcdFile, tmp_fu_131_p3, "tmp_fu_131_p3");
    sc_trace(mVcdFile, A_addr_6_reg_321, "A_addr_6_reg_321");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_74, "ap_sig_74");
    sc_trace(mVcdFile, tmp_31_fu_149_p3, "tmp_31_fu_149_p3");
    sc_trace(mVcdFile, p_Result_s_reg_326, "p_Result_s_reg_326");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_86, "ap_sig_86");
    sc_trace(mVcdFile, loc_V_2_fu_184_p1, "loc_V_2_fu_184_p1");
    sc_trace(mVcdFile, loc_V_2_reg_331, "loc_V_2_reg_331");
    sc_trace(mVcdFile, isNeg_fu_198_p3, "isNeg_fu_198_p3");
    sc_trace(mVcdFile, isNeg_reg_336, "isNeg_reg_336");
    sc_trace(mVcdFile, sh_assign_2_fu_216_p3, "sh_assign_2_fu_216_p3");
    sc_trace(mVcdFile, sh_assign_2_reg_341, "sh_assign_2_reg_341");
    sc_trace(mVcdFile, p_Val2_s_fu_292_p3, "p_Val2_s_fu_292_p3");
    sc_trace(mVcdFile, p_Val2_s_reg_347, "p_Val2_s_reg_347");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_101, "ap_sig_101");
    sc_trace(mVcdFile, grp_fu_128_p1, "grp_fu_128_p1");
    sc_trace(mVcdFile, tmp_2_i_reg_352, "tmp_2_i_reg_352");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_110, "ap_sig_110");
    sc_trace(mVcdFile, i_3_fu_299_p2, "i_3_fu_299_p2");
    sc_trace(mVcdFile, i_3_reg_357, "i_3_reg_357");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_119, "ap_sig_119");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_idle, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_idle");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_ready, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_ready");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address0, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address0");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce0, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce0");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we0, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we0");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d0, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d0");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address1, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address1");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce1, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce1");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we1, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we1");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d1, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d1");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA");
    sc_trace(mVcdFile, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA, "grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA");
    sc_trace(mVcdFile, i_reg_92, "i_reg_92");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_150, "ap_sig_150");
    sc_trace(mVcdFile, i_assign_reg_104, "i_assign_reg_104");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_162, "ap_sig_162");
    sc_trace(mVcdFile, ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start, "ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start");
    sc_trace(mVcdFile, tmp_i_fu_157_p1, "tmp_i_fu_157_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_181, "ap_sig_181");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_191, "ap_sig_191");
    sc_trace(mVcdFile, i_assign_cast_fu_145_p1, "i_assign_cast_fu_145_p1");
    sc_trace(mVcdFile, p_Val2_5_fu_162_p1, "p_Val2_5_fu_162_p1");
    sc_trace(mVcdFile, loc_V_fu_174_p4, "loc_V_fu_174_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i_cast1_fu_188_p1, "tmp_i_i_i_i_cast1_fu_188_p1");
    sc_trace(mVcdFile, sh_assign_fu_192_p2, "sh_assign_fu_192_p2");
    sc_trace(mVcdFile, tmp_2_i_i_i_fu_206_p2, "tmp_2_i_i_i_fu_206_p2");
    sc_trace(mVcdFile, tmp_2_i_i_i_cast_fu_212_p1, "tmp_2_i_i_i_cast_fu_212_p1");
    sc_trace(mVcdFile, p_Result_2_fu_224_p3, "p_Result_2_fu_224_p3");
    sc_trace(mVcdFile, sh_assign_2_cast_fu_235_p1, "sh_assign_2_cast_fu_235_p1");
    sc_trace(mVcdFile, sh_assign_2_cast_cast_fu_238_p1, "sh_assign_2_cast_cast_fu_238_p1");
    sc_trace(mVcdFile, tmp_i_i_i_fu_231_p1, "tmp_i_i_i_fu_231_p1");
    sc_trace(mVcdFile, tmp_3_i_i_i_fu_241_p1, "tmp_3_i_i_i_fu_241_p1");
    sc_trace(mVcdFile, tmp_4_i_i_i_fu_245_p2, "tmp_4_i_i_i_fu_245_p2");
    sc_trace(mVcdFile, tmp_37_fu_257_p3, "tmp_37_fu_257_p3");
    sc_trace(mVcdFile, tmp_6_i_i_i_fu_251_p2, "tmp_6_i_i_i_fu_251_p2");
    sc_trace(mVcdFile, tmp_s_fu_265_p1, "tmp_s_fu_265_p1");
    sc_trace(mVcdFile, tmp_27_fu_269_p4, "tmp_27_fu_269_p4");
    sc_trace(mVcdFile, p_Val2_8_fu_279_p3, "p_Val2_8_fu_279_p3");
    sc_trace(mVcdFile, p_Val2_7_i_i_i_fu_286_p2, "p_Val2_7_i_i_i_fu_286_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("heapSort_noRecurv.hdltvin.dat");
    mHdltvoutHandle.open("heapSort_noRecurv.hdltvout.dat");
}

heapSort_noRecurv::~heapSort_noRecurv() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116;
    delete heapSort_noRecurv_sitofp_32ns_32_6_U5;
}

void heapSort_noRecurv::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void heapSort_noRecurv::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
              esl_seteq<1,1,1>(tmp_fu_131_p3.read(), ap_const_lv1_0)) || 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
            ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_ready.read())) {
            ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(tmp_fu_131_p3.read(), ap_const_lv1_0))) {
        i_assign_reg_104 = ap_const_lv7_2F;
    } else if ((!esl_seteq<1,1,1>(ap_const_logic_0, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        i_assign_reg_104 = i_3_reg_357.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done.read()))) {
        i_reg_92 = i_2_reg_308.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_92 = ap_const_lv6_17;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_fu_149_p3.read()))) {
        A_addr_6_reg_321 =  (sc_lv<6>) (tmp_i_fu_157_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(tmp_fu_131_p3.read(), ap_const_lv1_0))) {
        i_2_reg_308 = i_2_fu_139_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        i_3_reg_357 = i_3_fu_299_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        isNeg_reg_336 = sh_assign_fu_192_p2.read().range(8, 8);
        loc_V_2_reg_331 = loc_V_2_fu_184_p1.read();
        p_Result_s_reg_326 = p_Val2_5_fu_162_p1.read().range(31, 31);
        sh_assign_2_reg_341 = sh_assign_2_fu_216_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        p_Val2_s_reg_347 = p_Val2_s_fu_292_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        tmp_2_i_reg_352 = grp_fu_128_p1.read();
    }
}

void heapSort_noRecurv::thread_A_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        A_address0 = A_addr_6_reg_321.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        A_address0 =  (sc_lv<6>) (tmp_i_fu_157_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_address0 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address0.read();
    } else {
        A_address0 = "XXXXXX";
    }
}

void heapSort_noRecurv::thread_A_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        A_address1 =  (sc_lv<6>) (ap_const_lv64_0);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_address1 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_address1.read();
    } else {
        A_address1 = "XXXXXX";
    }
}

void heapSort_noRecurv::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        A_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_ce0 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce0.read();
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_A_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        A_ce1 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_ce1 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_ce1.read();
    } else {
        A_ce1 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_A_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        A_d0 = A_q1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_d0 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d0.read();
    } else {
        A_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void heapSort_noRecurv::thread_A_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        A_d1 = tmp_2_i_reg_352.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_d1 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_d1.read();
    } else {
        A_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void heapSort_noRecurv::thread_A_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        A_we0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_we0 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we0.read();
    } else {
        A_we0 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_A_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        A_we1 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        A_we1 = grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_A_we1.read();
    } else {
        A_we1 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_fu_149_p3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_fu_149_p3.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_101() {
    ap_sig_101 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void heapSort_noRecurv::thread_ap_sig_110() {
    ap_sig_110 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void heapSort_noRecurv::thread_ap_sig_119() {
    ap_sig_119 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void heapSort_noRecurv::thread_ap_sig_150() {
    ap_sig_150 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void heapSort_noRecurv::thread_ap_sig_162() {
    ap_sig_162 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void heapSort_noRecurv::thread_ap_sig_181() {
    ap_sig_181 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void heapSort_noRecurv::thread_ap_sig_191() {
    ap_sig_191 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void heapSort_noRecurv::thread_ap_sig_30() {
    ap_sig_30 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void heapSort_noRecurv::thread_ap_sig_57() {
    ap_sig_57 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void heapSort_noRecurv::thread_ap_sig_74() {
    ap_sig_74 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void heapSort_noRecurv::thread_ap_sig_86() {
    ap_sig_86 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_110.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_181.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_119.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_162.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_30.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_57.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_150.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_74.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_86.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_101.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_191.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void heapSort_noRecurv::thread_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start() {
    grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start = ap_reg_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_start.read();
}

void heapSort_noRecurv::thread_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA = i_assign_reg_104.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA = ap_const_lv7_30;
    } else {
        grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_endA =  (sc_lv<7>) ("XXXXXXX");
    }
}

void heapSort_noRecurv::thread_grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA = i_reg_92.read();
    } else {
        grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_startA = "XXXXXX";
    }
}

void heapSort_noRecurv::thread_i_2_fu_139_p2() {
    i_2_fu_139_p2 = (!i_reg_92.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(i_reg_92.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void heapSort_noRecurv::thread_i_3_fu_299_p2() {
    i_3_fu_299_p2 = (!ap_const_lv7_7F.is_01() || !i_assign_reg_104.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_7F) + sc_biguint<7>(i_assign_reg_104.read()));
}

void heapSort_noRecurv::thread_i_assign_cast_fu_145_p1() {
    i_assign_cast_fu_145_p1 = esl_sext<32,7>(i_assign_reg_104.read());
}

void heapSort_noRecurv::thread_isNeg_fu_198_p3() {
    isNeg_fu_198_p3 = sh_assign_fu_192_p2.read().range(8, 8);
}

void heapSort_noRecurv::thread_loc_V_2_fu_184_p1() {
    loc_V_2_fu_184_p1 = p_Val2_5_fu_162_p1.read().range(23-1, 0);
}

void heapSort_noRecurv::thread_loc_V_fu_174_p4() {
    loc_V_fu_174_p4 = p_Val2_5_fu_162_p1.read().range(30, 23);
}

void heapSort_noRecurv::thread_p_Result_2_fu_224_p3() {
    p_Result_2_fu_224_p3 = esl_concat<1,23>(ap_const_lv1_1, loc_V_2_reg_331.read());
}

void heapSort_noRecurv::thread_p_Val2_5_fu_162_p1() {
    p_Val2_5_fu_162_p1 = A_q0.read();
}

void heapSort_noRecurv::thread_p_Val2_7_i_i_i_fu_286_p2() {
    p_Val2_7_i_i_i_fu_286_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_8_fu_279_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_8_fu_279_p3.read()));
}

void heapSort_noRecurv::thread_p_Val2_8_fu_279_p3() {
    p_Val2_8_fu_279_p3 = (!isNeg_reg_336.read()[0].is_01())? sc_lv<32>(): ((isNeg_reg_336.read()[0].to_bool())? tmp_s_fu_265_p1.read(): tmp_27_fu_269_p4.read());
}

void heapSort_noRecurv::thread_p_Val2_s_fu_292_p3() {
    p_Val2_s_fu_292_p3 = (!p_Result_s_reg_326.read()[0].is_01())? sc_lv<32>(): ((p_Result_s_reg_326.read()[0].to_bool())? p_Val2_7_i_i_i_fu_286_p2.read(): p_Val2_8_fu_279_p3.read());
}

void heapSort_noRecurv::thread_sh_assign_2_cast_cast_fu_238_p1() {
    sh_assign_2_cast_cast_fu_238_p1 = esl_sext<24,9>(sh_assign_2_reg_341.read());
}

void heapSort_noRecurv::thread_sh_assign_2_cast_fu_235_p1() {
    sh_assign_2_cast_fu_235_p1 = esl_sext<32,9>(sh_assign_2_reg_341.read());
}

void heapSort_noRecurv::thread_sh_assign_2_fu_216_p3() {
    sh_assign_2_fu_216_p3 = (!isNeg_fu_198_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_198_p3.read()[0].to_bool())? tmp_2_i_i_i_cast_fu_212_p1.read(): sh_assign_fu_192_p2.read());
}

void heapSort_noRecurv::thread_sh_assign_fu_192_p2() {
    sh_assign_fu_192_p2 = (!ap_const_lv9_181.is_01() || !tmp_i_i_i_i_cast1_fu_188_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_181) + sc_biguint<9>(tmp_i_i_i_i_cast1_fu_188_p1.read()));
}

void heapSort_noRecurv::thread_tmp_27_fu_269_p4() {
    tmp_27_fu_269_p4 = tmp_6_i_i_i_fu_251_p2.read().range(54, 23);
}

void heapSort_noRecurv::thread_tmp_2_i_i_i_cast_fu_212_p1() {
    tmp_2_i_i_i_cast_fu_212_p1 = esl_sext<9,8>(tmp_2_i_i_i_fu_206_p2.read());
}

void heapSort_noRecurv::thread_tmp_2_i_i_i_fu_206_p2() {
    tmp_2_i_i_i_fu_206_p2 = (!ap_const_lv8_7F.is_01() || !loc_V_fu_174_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(loc_V_fu_174_p4.read()));
}

void heapSort_noRecurv::thread_tmp_31_fu_149_p3() {
    tmp_31_fu_149_p3 = i_assign_reg_104.read().range(6, 6);
}

void heapSort_noRecurv::thread_tmp_37_fu_257_p3() {
    tmp_37_fu_257_p3 = tmp_4_i_i_i_fu_245_p2.read().range(23, 23);
}

void heapSort_noRecurv::thread_tmp_3_i_i_i_fu_241_p1() {
    tmp_3_i_i_i_fu_241_p1 = esl_zext<78,32>(sh_assign_2_cast_fu_235_p1.read());
}

void heapSort_noRecurv::thread_tmp_4_i_i_i_fu_245_p2() {
    tmp_4_i_i_i_fu_245_p2 = (!sh_assign_2_cast_cast_fu_238_p1.read().is_01())? sc_lv<24>(): p_Result_2_fu_224_p3.read() >> (unsigned short)sh_assign_2_cast_cast_fu_238_p1.read().to_uint();
}

void heapSort_noRecurv::thread_tmp_6_i_i_i_fu_251_p2() {
    tmp_6_i_i_i_fu_251_p2 = (!tmp_3_i_i_i_fu_241_p1.read().is_01())? sc_lv<78>(): tmp_i_i_i_fu_231_p1.read() << (unsigned short)tmp_3_i_i_i_fu_241_p1.read().to_uint();
}

void heapSort_noRecurv::thread_tmp_fu_131_p3() {
    tmp_fu_131_p3 = i_reg_92.read().range(5, 5);
}

void heapSort_noRecurv::thread_tmp_i_fu_157_p1() {
    tmp_i_fu_157_p1 = esl_zext<64,32>(i_assign_cast_fu_145_p1.read());
}

void heapSort_noRecurv::thread_tmp_i_i_i_fu_231_p1() {
    tmp_i_i_i_fu_231_p1 = esl_zext<78,24>(p_Result_2_fu_224_p3.read());
}

void heapSort_noRecurv::thread_tmp_i_i_i_i_cast1_fu_188_p1() {
    tmp_i_i_i_i_cast1_fu_188_p1 = esl_zext<9,8>(loc_V_fu_174_p4.read());
}

void heapSort_noRecurv::thread_tmp_s_fu_265_p1() {
    tmp_s_fu_265_p1 = esl_zext<32,1>(tmp_37_fu_257_p3.read());
}

void heapSort_noRecurv::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(tmp_fu_131_p3.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_fu_149_p3.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_heapSort_noRecurv_maxHeapify_noRecurv_fu_116_ap_done.read())) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

void heapSort_noRecurv::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address0\" :  \"" << A_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce0\" :  \"" << A_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_we0\" :  \"" << A_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_d0\" :  \"" << A_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q0\" :  \"" << A_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address1\" :  \"" << A_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce1\" :  \"" << A_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_we1\" :  \"" << A_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_d1\" :  \"" << A_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q1\" :  \"" << A_q1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

