// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "shellSort.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic shellSort::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic shellSort::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> shellSort::ap_ST_st1_fsm_0 = "1";
const sc_lv<6> shellSort::ap_ST_st2_fsm_1 = "10";
const sc_lv<6> shellSort::ap_ST_st3_fsm_2 = "100";
const sc_lv<6> shellSort::ap_ST_st4_fsm_3 = "1000";
const sc_lv<6> shellSort::ap_ST_st5_fsm_4 = "10000";
const sc_lv<6> shellSort::ap_ST_st6_fsm_5 = "100000";
const sc_lv<32> shellSort::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> shellSort::ap_const_lv1_1 = "1";
const sc_lv<32> shellSort::ap_const_lv32_1 = "1";
const sc_lv<1> shellSort::ap_const_lv1_0 = "0";
const sc_lv<32> shellSort::ap_const_lv32_2 = "10";
const sc_lv<32> shellSort::ap_const_lv32_3 = "11";
const sc_lv<32> shellSort::ap_const_lv32_4 = "100";
const sc_lv<32> shellSort::ap_const_lv32_5 = "101";
const sc_lv<32> shellSort::ap_const_lv32_30 = "110000";
const sc_lv<32> shellSort::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> shellSort::ap_const_lv32_17 = "10111";
const sc_lv<32> shellSort::ap_const_lv32_1E = "11110";
const sc_lv<8> shellSort::ap_const_lv8_FF = "11111111";
const sc_lv<23> shellSort::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> shellSort::ap_const_lv5_3 = "11";

shellSort::shellSort(sc_module_name name) : sc_module(name), mVcdFile(0) {
    shellSort_fcmp_32ns_32ns_1_1_U0 = new shellSort_fcmp_32ns_32ns_1_1<1,1,32,32,1>("shellSort_fcmp_32ns_32ns_1_1_U0");
    shellSort_fcmp_32ns_32ns_1_1_U0->din0(A_load_reg_251);
    shellSort_fcmp_32ns_32ns_1_1_U0->din1(A_load_1_reg_257);
    shellSort_fcmp_32ns_32ns_1_1_U0->opcode(ap_var_for_const0);
    shellSort_fcmp_32ns_32ns_1_1_U0->dout(tmp_10_fu_64_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( A_addr_1_reg_245 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_4_fu_102_p1 );
    sensitive << ( tmp_i_fu_198_p1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_A_address1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( A_addr_2_reg_268 );
    sensitive << ( tmp_6_fu_111_p1 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_A_ce1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_A_d0);
    sensitive << ( A_q0 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_A_d1);
    sensitive << ( A_load_1_reg_257 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_A_load_1_to_int_fu_133_p1);
    sensitive << ( A_load_1_reg_257 );

    SC_METHOD(thread_A_load_to_int_fu_116_p1);
    sensitive << ( A_load_reg_251 );

    SC_METHOD(thread_A_we0);
    sensitive << ( tmp_11_reg_264 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_A_we1);
    sensitive << ( tmp_11_reg_264 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_76_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_76_p2 );

    SC_METHOD(thread_ap_sig_108);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_48);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_62);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_84);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_48 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_62 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_74 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_84 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_108 );

    SC_METHOD(thread_i_assign_fu_94_p3);
    sensitive << ( index_3_fu_28 );
    sensitive << ( tmp_2_fu_82_p2 );
    sensitive << ( index_fu_88_p2 );

    SC_METHOD(thread_index_1_fu_206_p2);
    sensitive << ( i_assign_reg_227 );

    SC_METHOD(thread_index_2_fu_106_p2);
    sensitive << ( i_assign_reg_227 );

    SC_METHOD(thread_index_fu_88_p2);
    sensitive << ( index_3_fu_28 );

    SC_METHOD(thread_notlhs1_fu_168_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_5_fu_136_p4 );

    SC_METHOD(thread_notlhs_fu_150_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_1_fu_119_p4 );

    SC_METHOD(thread_notrhs2_fu_174_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_7_fu_146_p1 );

    SC_METHOD(thread_notrhs_fu_156_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp_3_fu_129_p1 );

    SC_METHOD(thread_tmp_11_fu_192_p2);
    sensitive << ( tmp_s_fu_186_p2 );
    sensitive << ( tmp_10_fu_64_p2 );

    SC_METHOD(thread_tmp_1_fu_119_p4);
    sensitive << ( A_load_to_int_fu_116_p1 );

    SC_METHOD(thread_tmp_2_fu_82_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_fu_76_p2 );
    sensitive << ( index_3_fu_28 );

    SC_METHOD(thread_tmp_3_fu_129_p1);
    sensitive << ( A_load_to_int_fu_116_p1 );

    SC_METHOD(thread_tmp_4_fu_102_p1);
    sensitive << ( i_assign_reg_227 );

    SC_METHOD(thread_tmp_5_fu_136_p4);
    sensitive << ( A_load_1_to_int_fu_133_p1 );

    SC_METHOD(thread_tmp_6_fu_111_p1);
    sensitive << ( index_2_fu_106_p2 );

    SC_METHOD(thread_tmp_7_fu_146_p1);
    sensitive << ( A_load_1_to_int_fu_133_p1 );

    SC_METHOD(thread_tmp_8_fu_162_p2);
    sensitive << ( notrhs_fu_156_p2 );
    sensitive << ( notlhs_fu_150_p2 );

    SC_METHOD(thread_tmp_9_fu_180_p2);
    sensitive << ( notrhs2_fu_174_p2 );
    sensitive << ( notlhs1_fu_168_p2 );

    SC_METHOD(thread_tmp_fu_76_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( index_3_fu_28 );

    SC_METHOD(thread_tmp_i_fu_198_p1);
    sensitive << ( i_assign_reg_227 );

    SC_METHOD(thread_tmp_s_fu_186_p2);
    sensitive << ( tmp_8_fu_162_p2 );
    sensitive << ( tmp_9_fu_180_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_76_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "shellSort_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_we0, "(port)A_we0");
    sc_trace(mVcdFile, A_d0, "(port)A_d0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, A_address1, "(port)A_address1");
    sc_trace(mVcdFile, A_ce1, "(port)A_ce1");
    sc_trace(mVcdFile, A_we1, "(port)A_we1");
    sc_trace(mVcdFile, A_d1, "(port)A_d1");
    sc_trace(mVcdFile, A_q1, "(port)A_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_21, "ap_sig_21");
    sc_trace(mVcdFile, i_assign_fu_94_p3, "i_assign_fu_94_p3");
    sc_trace(mVcdFile, i_assign_reg_227, "i_assign_reg_227");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_48, "ap_sig_48");
    sc_trace(mVcdFile, tmp_fu_76_p2, "tmp_fu_76_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_62, "ap_sig_62");
    sc_trace(mVcdFile, index_2_fu_106_p2, "index_2_fu_106_p2");
    sc_trace(mVcdFile, index_2_reg_240, "index_2_reg_240");
    sc_trace(mVcdFile, A_addr_1_reg_245, "A_addr_1_reg_245");
    sc_trace(mVcdFile, A_load_reg_251, "A_load_reg_251");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_74, "ap_sig_74");
    sc_trace(mVcdFile, A_load_1_reg_257, "A_load_1_reg_257");
    sc_trace(mVcdFile, tmp_11_fu_192_p2, "tmp_11_fu_192_p2");
    sc_trace(mVcdFile, tmp_11_reg_264, "tmp_11_reg_264");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_84, "ap_sig_84");
    sc_trace(mVcdFile, A_addr_2_reg_268, "A_addr_2_reg_268");
    sc_trace(mVcdFile, tmp_4_fu_102_p1, "tmp_4_fu_102_p1");
    sc_trace(mVcdFile, tmp_6_fu_111_p1, "tmp_6_fu_111_p1");
    sc_trace(mVcdFile, tmp_i_fu_198_p1, "tmp_i_fu_198_p1");
    sc_trace(mVcdFile, index_3_fu_28, "index_3_fu_28");
    sc_trace(mVcdFile, index_1_fu_206_p2, "index_1_fu_206_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_108, "ap_sig_108");
    sc_trace(mVcdFile, tmp_2_fu_82_p2, "tmp_2_fu_82_p2");
    sc_trace(mVcdFile, index_fu_88_p2, "index_fu_88_p2");
    sc_trace(mVcdFile, A_load_to_int_fu_116_p1, "A_load_to_int_fu_116_p1");
    sc_trace(mVcdFile, A_load_1_to_int_fu_133_p1, "A_load_1_to_int_fu_133_p1");
    sc_trace(mVcdFile, tmp_1_fu_119_p4, "tmp_1_fu_119_p4");
    sc_trace(mVcdFile, tmp_3_fu_129_p1, "tmp_3_fu_129_p1");
    sc_trace(mVcdFile, notrhs_fu_156_p2, "notrhs_fu_156_p2");
    sc_trace(mVcdFile, notlhs_fu_150_p2, "notlhs_fu_150_p2");
    sc_trace(mVcdFile, tmp_5_fu_136_p4, "tmp_5_fu_136_p4");
    sc_trace(mVcdFile, tmp_7_fu_146_p1, "tmp_7_fu_146_p1");
    sc_trace(mVcdFile, notrhs2_fu_174_p2, "notrhs2_fu_174_p2");
    sc_trace(mVcdFile, notlhs1_fu_168_p2, "notlhs1_fu_168_p2");
    sc_trace(mVcdFile, tmp_8_fu_162_p2, "tmp_8_fu_162_p2");
    sc_trace(mVcdFile, tmp_9_fu_180_p2, "tmp_9_fu_180_p2");
    sc_trace(mVcdFile, tmp_s_fu_186_p2, "tmp_s_fu_186_p2");
    sc_trace(mVcdFile, tmp_10_fu_64_p2, "tmp_10_fu_64_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("shellSort.hdltvin.dat");
    mHdltvoutHandle.open("shellSort.hdltvout.dat");
}

shellSort::~shellSort() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete shellSort_fcmp_32ns_32ns_1_1_U0;
}

void shellSort::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv5_3;
}

void shellSort::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_192_p2.read()))) {
        index_3_fu_28 = index_1_fu_206_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_192_p2.read()))) {
        index_3_fu_28 = index_2_reg_240.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        index_3_fu_28 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        A_addr_1_reg_245 =  (sc_lv<6>) (tmp_6_fu_111_p1.read());
        index_2_reg_240 = index_2_fu_106_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_fu_192_p2.read()))) {
        A_addr_2_reg_268 =  (sc_lv<6>) (tmp_i_fu_198_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        A_load_1_reg_257 = A_q1.read();
        A_load_reg_251 = A_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(tmp_fu_76_p2.read(), ap_const_lv1_0))) {
        i_assign_reg_227 = i_assign_fu_94_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        tmp_11_reg_264 = tmp_11_fu_192_p2.read();
    }
}

void shellSort::thread_A_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        A_address0 = A_addr_1_reg_245.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        A_address0 =  (sc_lv<6>) (tmp_i_fu_198_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        A_address0 =  (sc_lv<6>) (tmp_4_fu_102_p1.read());
    } else {
        A_address0 = "XXXXXX";
    }
}

void shellSort::thread_A_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        A_address1 = A_addr_2_reg_268.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        A_address1 =  (sc_lv<6>) (tmp_6_fu_111_p1.read());
    } else {
        A_address1 = "XXXXXX";
    }
}

void shellSort::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void shellSort::thread_A_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        A_ce1 = ap_const_logic_1;
    } else {
        A_ce1 = ap_const_logic_0;
    }
}

void shellSort::thread_A_d0() {
    A_d0 = A_q0.read();
}

void shellSort::thread_A_d1() {
    A_d1 = A_load_1_reg_257.read();
}

void shellSort::thread_A_load_1_to_int_fu_133_p1() {
    A_load_1_to_int_fu_133_p1 = A_load_1_reg_257.read();
}

void shellSort::thread_A_load_to_int_fu_116_p1() {
    A_load_to_int_fu_116_p1 = A_load_reg_251.read();
}

void shellSort::thread_A_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_reg_264.read())))) {
        A_we0 = ap_const_logic_1;
    } else {
        A_we0 = ap_const_logic_0;
    }
}

void shellSort::thread_A_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_11_reg_264.read())))) {
        A_we1 = ap_const_logic_1;
    } else {
        A_we1 = ap_const_logic_0;
    }
}

void shellSort::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_fu_76_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void shellSort::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void shellSort::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_fu_76_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void shellSort::thread_ap_sig_108() {
    ap_sig_108 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void shellSort::thread_ap_sig_21() {
    ap_sig_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void shellSort::thread_ap_sig_48() {
    ap_sig_48 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void shellSort::thread_ap_sig_62() {
    ap_sig_62 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void shellSort::thread_ap_sig_74() {
    ap_sig_74 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void shellSort::thread_ap_sig_84() {
    ap_sig_84 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void shellSort::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void shellSort::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_48.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void shellSort::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_62.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void shellSort::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_74.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void shellSort::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_84.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void shellSort::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_108.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void shellSort::thread_i_assign_fu_94_p3() {
    i_assign_fu_94_p3 = (!tmp_2_fu_82_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_2_fu_82_p2.read()[0].to_bool())? index_fu_88_p2.read(): index_3_fu_28.read());
}

void shellSort::thread_index_1_fu_206_p2() {
    index_1_fu_206_p2 = (!i_assign_reg_227.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i_assign_reg_227.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void shellSort::thread_index_2_fu_106_p2() {
    index_2_fu_106_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !i_assign_reg_227.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(i_assign_reg_227.read()));
}

void shellSort::thread_index_fu_88_p2() {
    index_fu_88_p2 = (!ap_const_lv32_1.is_01() || !index_3_fu_28.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(index_3_fu_28.read()));
}

void shellSort::thread_notlhs1_fu_168_p2() {
    notlhs1_fu_168_p2 = (!tmp_5_fu_136_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_5_fu_136_p4.read() != ap_const_lv8_FF);
}

void shellSort::thread_notlhs_fu_150_p2() {
    notlhs_fu_150_p2 = (!tmp_1_fu_119_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_119_p4.read() != ap_const_lv8_FF);
}

void shellSort::thread_notrhs2_fu_174_p2() {
    notrhs2_fu_174_p2 = (!tmp_7_fu_146_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_7_fu_146_p1.read() == ap_const_lv23_0);
}

void shellSort::thread_notrhs_fu_156_p2() {
    notrhs_fu_156_p2 = (!tmp_3_fu_129_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_3_fu_129_p1.read() == ap_const_lv23_0);
}

void shellSort::thread_tmp_11_fu_192_p2() {
    tmp_11_fu_192_p2 = (tmp_s_fu_186_p2.read() & tmp_10_fu_64_p2.read());
}

void shellSort::thread_tmp_1_fu_119_p4() {
    tmp_1_fu_119_p4 = A_load_to_int_fu_116_p1.read().range(30, 23);
}

void shellSort::thread_tmp_2_fu_82_p2() {
    tmp_2_fu_82_p2 = (!index_3_fu_28.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(index_3_fu_28.read() == ap_const_lv32_0);
}

void shellSort::thread_tmp_3_fu_129_p1() {
    tmp_3_fu_129_p1 = A_load_to_int_fu_116_p1.read().range(23-1, 0);
}

void shellSort::thread_tmp_4_fu_102_p1() {
    tmp_4_fu_102_p1 = esl_sext<64,32>(i_assign_reg_227.read());
}

void shellSort::thread_tmp_5_fu_136_p4() {
    tmp_5_fu_136_p4 = A_load_1_to_int_fu_133_p1.read().range(30, 23);
}

void shellSort::thread_tmp_6_fu_111_p1() {
    tmp_6_fu_111_p1 = esl_sext<64,32>(index_2_fu_106_p2.read());
}

void shellSort::thread_tmp_7_fu_146_p1() {
    tmp_7_fu_146_p1 = A_load_1_to_int_fu_133_p1.read().range(23-1, 0);
}

void shellSort::thread_tmp_8_fu_162_p2() {
    tmp_8_fu_162_p2 = (notrhs_fu_156_p2.read() | notlhs_fu_150_p2.read());
}

void shellSort::thread_tmp_9_fu_180_p2() {
    tmp_9_fu_180_p2 = (notrhs2_fu_174_p2.read() | notlhs1_fu_168_p2.read());
}

void shellSort::thread_tmp_fu_76_p2() {
    tmp_fu_76_p2 = (!index_3_fu_28.read().is_01() || !ap_const_lv32_30.is_01())? sc_lv<1>(): (sc_bigint<32>(index_3_fu_28.read()) < sc_bigint<32>(ap_const_lv32_30));
}

void shellSort::thread_tmp_i_fu_198_p1() {
    tmp_i_fu_198_p1 = esl_zext<64,32>(i_assign_reg_227.read());
}

void shellSort::thread_tmp_s_fu_186_p2() {
    tmp_s_fu_186_p2 = (tmp_8_fu_162_p2.read() & tmp_9_fu_180_p2.read());
}

void shellSort::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(tmp_fu_76_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

void shellSort::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address0\" :  \"" << A_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce0\" :  \"" << A_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_we0\" :  \"" << A_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_d0\" :  \"" << A_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q0\" :  \"" << A_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address1\" :  \"" << A_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce1\" :  \"" << A_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_we1\" :  \"" << A_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_d1\" :  \"" << A_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q1\" :  \"" << A_q1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

